/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2019-12-23 01:54:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template.compiler;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/png\" href=\"../../img/favicon.png\">\r\n");
      out.write("    <title>flow_compiler</title>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/flow/mcgfn.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/flow/addition.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        var seed = Math.random();\r\n");
      out.write("        var text = \"\";\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $(\"#select\").change(function() { // TODO: 2019/12/6 15:27 not react if select the same file\r\n");
      out.write("                text = \"\";\r\n");
      out.write("                var file = this.files[0];\r\n");
      out.write("                if (file == undefined || file == \" \") {\r\n");
      out.write("                    $(\"#code\").text(\"\");\r\n");
      out.write("                    $(\"#code\").children(\" p \").each(function () {\r\n");
      out.write("                        $(this).remove();\r\n");
      out.write("                    })\r\n");
      out.write("                }\r\n");
      out.write("                var reader = new FileReader();\r\n");
      out.write("                reader.readAsText(file);\r\n");
      out.write("                reader.onload = function () {\r\n");
      out.write("                    var strList = this.result.split(\"\\n\");\r\n");
      out.write("                    var len = strList.length;\r\n");
      out.write("                    $(\"#code\").children(\" p \").each(function () {\r\n");
      out.write("                        $(this).remove();\r\n");
      out.write("                    })\r\n");
      out.write("                    for(var i = 0 ;i <len ; i++){\r\n");
      out.write("                        text += strList[i];\r\n");
      out.write("                         $(\"#code\").append(\"<p>\" +strList[i]+\"</p>\");\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#compiler\").bind(\"click\",function () {\r\n");
      out.write("                var form = $(\"<form>\");\r\n");
      out.write("                form.attr(\"style\", \"display:none\");\r\n");
      out.write("                form.attr(\"method\", \"post\");\r\n");
      out.write("                form.attr(\"action\", baseUrl + \"/tool/compiler\");\r\n");
      out.write("                var flowIdInput = $(\"<input>\");\r\n");
      out.write("                flowIdInput.attr(\"type\",\"hidden\");\r\n");
      out.write("                flowIdInput.attr(\"name\",\"text\");\r\n");
      out.write("                flowIdInput.attr(\"value\",text);\r\n");
      out.write("                alert(text);\r\n");
      out.write("                form.append(flowIdInput);\r\n");
      out.write("                flowIdInput = $(\"<input>\");\r\n");
      out.write("                flowIdInput.attr(\"type\",\"hidden\");\r\n");
      out.write("                flowIdInput.attr(\"name\",\"random\");\r\n");
      out.write("                flowIdInput.attr(\"value\",seed);\r\n");
      out.write("                form.append(flowIdInput)\r\n");
      out.write("                $(\"#compiler\").append(form);\r\n");
      out.write("\r\n");
      out.write("                form.submit();\r\n");
      out.write("                form.remove();\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 主面body开始 -->\r\n");
      out.write("<div id=\"mcg_body\" class=\"container-fluid autoHeight\" >\r\n");
      out.write("    <div class=\"row autoHeight\" style=\"width:30% ; height: 20%\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <input id=\"select\"  type=\"file\" style=\"float:left ;\" >select\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("\r\n");
      out.write("            <button id = \"compiler\" style=\"float: left \"  >compiler</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <div style=\"width: 100% ;height: 80% ;background: #5bc0de; clear: both; overflow: scroll\" id = \"code\" >\r\n");
      out.write("        <p style=\"width: 100% ;height:100% \"  name = \"code\"></p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 主面body结束 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
