/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2019-12-23 01:54:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- \r\n");
      out.write("/*\r\n");
      out.write(" * @Copyright (c) 2018 缪聪(mcg-helper@qq.com)\r\n");
      out.write(" * \r\n");
      out.write(" * Licensed under the Apache License, Version 2.0 (the \"License\");  \r\n");
      out.write(" * you may not use this file except in compliance with the License.  \r\n");
      out.write(" * You may obtain a copy of the License at  \r\n");
      out.write(" *     \r\n");
      out.write(" *     http://www.apache.org/licenses/LICENSE-2.0  \r\n");
      out.write(" *     \r\n");
      out.write(" * Unless required by applicable law or agreed to in writing, software  \r\n");
      out.write(" * distributed under the License is distributed on an \"AS IS\" BASIS,  \r\n");
      out.write(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  \r\n");
      out.write(" * See the License for the specific language governing permissions and  \r\n");
      out.write(" * limitations under the License.\r\n");
      out.write(" */\r\n");
      out.write(" -->\r\n");
      out.write(" \r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<link rel=\"shortcut icon\"  href=\"");
      out.print(basePath );
      out.write("/favicon.ico\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"");
      out.print(basePath );
      out.write("/library/js/jquery-1.12.2.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath );
      out.write("/library/js/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<title>mcg-helper研发助手</title>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('#loginBtn').on('click', function () {\r\n");
      out.write(" \t\t\t\tvar $btn = $(this).button('loading');\r\n");
      out.write("\t\t\t\t$(\"#loginForm\").submit(); \r\n");
      out.write("\t\t\t//\t$btn.button('reset');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<form id=\"loginForm\" class=\"form-signin\" action=\"");
      out.print(basePath );
      out.write("/login\" method=\"post\">\r\n");
      out.write("\t        <div class=\"modal-dialog\" style=\"margin-top: 15%;\">\r\n");
      out.write("\t            <div class=\"modal-content\">\r\n");
      out.write("\t                <div class=\"modal-header\">\r\n");
      out.write("\t                    <h4 class=\"modal-title\">欢迎使用Data-Flow</h4>\r\n");
      out.write("\t                </div>\r\n");
      out.write(" \t                \r\n");
      out.write("\t                <div class=\"modal-body\">\r\n");
      out.write("\t                    \r\n");
      out.write("\t                \t<input type=\"hidden\" name=\"userKey\" value=\"test\" placeholder=\"\" autocomplete=\"off\" class=\"form-control placeholder-no-fix\">\r\n");
      out.write("\t                \t<div class=\"form-body\">\r\n");
      out.write("\t                \t\r\n");
      out.write("\t                \t\t<div class=\"form-group\">\r\n");
      out.write("\t                    \t\t<button id=\"loginBtn\" class=\"btn btn-primary pull-right\" type=\"button\">进入系统</button>\r\n");
      out.write("\t                    \t\t<br/>\r\n");
      out.write("\t                    \t</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    \t\r\n");
      out.write("\t                </div>\r\n");
      out.write("<!--  \t                 \r\n");
      out.write("\t                <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                 -->\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\t</div>            \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
