/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2019-12-23 01:54:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/template/common.jsp", Long.valueOf(1574749557227L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- \r\n");
      out.write("/*\r\n");
      out.write(" * @Copyright (c) 2018 缪聪(mcg-helper@qq.com)\r\n");
      out.write(" * \r\n");
      out.write(" * Licensed under the Apache License, Version 2.0 (the \"License\");  \r\n");
      out.write(" * you may not use this file except in compliance with the License.  \r\n");
      out.write(" * You may obtain a copy of the License at  \r\n");
      out.write(" *     \r\n");
      out.write(" *     http://www.apache.org/licenses/LICENSE-2.0  \r\n");
      out.write(" *     \r\n");
      out.write(" * Unless required by applicable law or agreed to in writing, software  \r\n");
      out.write(" * distributed under the License is distributed on an \"AS IS\" BASIS,  \r\n");
      out.write(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  \r\n");
      out.write(" * See the License for the specific language governing permissions and  \r\n");
      out.write(" * limitations under the License.\r\n");
      out.write(" */\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>data_flow</title>\r\n");
      out.write("\t");
      out.write("<!-- \r\n");
      out.write("/*\r\n");
      out.write(" * @Copyright (c) 2018 缪聪(mcg-helper@qq.com)\r\n");
      out.write(" * \r\n");
      out.write(" * Licensed under the Apache License, Version 2.0 (the \"License\");  \r\n");
      out.write(" * you may not use this file except in compliance with the License.  \r\n");
      out.write(" * You may obtain a copy of the License at  \r\n");
      out.write(" *     \r\n");
      out.write(" *     http://www.apache.org/licenses/LICENSE-2.0  \r\n");
      out.write(" *     \r\n");
      out.write(" * Unless required by applicable law or agreed to in writing, software  \r\n");
      out.write(" * distributed under the License is distributed on an \"AS IS\" BASIS,  \r\n");
      out.write(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  \r\n");
      out.write(" * See the License for the specific language governing permissions and  \r\n");
      out.write(" * limitations under the License.\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/css/font-awesome/css/font-awesome.min.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/ztree/css/awesomeStyle/awesome.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text/css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/bootstrap/css/bootstrap.min.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/bootstrap/select-1.12.1/css/bootstrap-select.min.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/bootstraptable/css/bootstrap-table.min.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/jquery-ui-1.12.1/jquery-ui-1.10.0.custom.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/bootstrap-switch/css/bootstrap-switch.min.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/messenger/css/messenger.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/messenger/css/messenger-theme-air.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/js/jsoneditor/jsoneditor.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/css/flow/core.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/css/flow/drage.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/css/addition.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/jquery-1.12.2.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/jquery-ui-1.12.1/jquery-ui.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/jquery.goup.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/bootstrap/js/bootstrap.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/ztree/js/jquery.ztree.core.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/ztree/js/jquery.ztree.excheck.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/ztree/js/jquery.ztree.exedit.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/bootstrap-switch/js/bootstrap-switch.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/bootstraptable/js/bootstrap-table.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/bootstraptable/locale/bootstrap-table-zh-CN.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/messenger/js/messenger.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/ace/ace.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/ace/ext-language_tools.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/ace/source-code-pro/source-code-pro.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/bootstrap/select-1.12.1/js/bootstrap-select.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/jsoneditor/jsoneditor-minimalist.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/jquery.serialize-object.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/jquery.form.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/reconnecting-websocket.min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/common.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/jquery.jsPlumb-1.7.5-min.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/flow/initmodal.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/flow/wigdet.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/library/js/flow/htmlmodel.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar baseUrl = '");
      out.print(basePath );
      out.write("';\r\n");
      out.write("\t\tvar websocketUrl = \"ws:\" + baseUrl.replace(\"http:\", \"\") + \"/message\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar mcgWebSocket = {\r\n");
      out.write("\t\t\topen : function () {\r\n");
      out.write("\t\t\t\tws = new ReconnectingWebSocket(websocketUrl);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tws.onmessage = function (e) {\r\n");
      out.write("\t\t  \t\t\tvar message = new Message({\r\n");
      out.write("\t\t\t\t\t\tmsg : JSON.parse(event.data)\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tmessage.output();\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tws.onopen = function (e) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tws.onclose = function (e) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tws.onerror = function (e) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsend : function (x) {\r\n");
      out.write("\t\t\t\tws.send(x);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tmcgWebSocket.open();\r\n");
      out.write("\t\t \r\n");
      out.write("\t</script>");
      out.write("\r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(basePath );
      out.write("/favicon.ico\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath );
      out.write("/library/css/index.css?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<script src=\"");
      out.print(basePath );
      out.write("/library/js/index.js?_v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- head开始 -->\r\n");
      out.write("\t<div id=\"mcg_header\" class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row \">\r\n");
      out.write("\t\t    <div class=\"mcg_header\">\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- head结束 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- tips开始 -->\r\n");
      out.write("\t<div id=\"mcg_tips\" class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- tips结束 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- main开始 -->\r\n");
      out.write("\t<div id=\"mcg_main\" class=\"container-fluid autoHeight\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div id=\"mcg_nav\" class=\"mcg_main_nav_header\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-header pull-right\">\r\n");
      out.write("\t\t\t\t\t\t <a class=\"navbar-brand\" href=\"https://github.com/mcg-helper/mcg-helper\" target=\"_blank\">Data-Flow</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-pills\" role=\"tablist\" id=\"mcgTab\">\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#mcg_flow\" data-toggle=\"tab\">工作台</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"#mcg_compiler\" data-toggle=\"tab\">文件编译</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row autoHeight\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 autoHeight\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"tab-content autoHeight\">\r\n");
      out.write("\t\t\t\t\t<div id=\"mcg_flow\" class=\"tab-pane active mcg_main_highlight autoHeight\" style=\"overflow-x: auto;overflow-y: auto;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"mcg_compiler\" class=\"tab-pane mcg_main_highlight autoHeight\"  style=\"overflow-x: auto;overflow-y: auto;\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- main结束 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- footer开始  navbar-fixed-bottom \r\n");
      out.write("\t<div id=\"mcg_footer\" class=\"container-fluid mcg_footer\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t如有问题或建议请发送邮件到mcg-helper@qq.com进行反馈与交流，感谢您的支持！\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t   \tCopyright © 2018, mcg-helper@qq.com, All Rights Reserved\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("\t<!-- footer结束 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
