/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2019-12-23 01:54:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class flowSuspension_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- \r\n");
      out.write("/*\r\n");
      out.write(" * @Copyright (c) 2018 缪聪(mcg-helper@qq.com)\r\n");
      out.write(" * \r\n");
      out.write(" * Licensed under the Apache License, Version 2.0 (the \"License\");  \r\n");
      out.write(" * you may not use this file except in compliance with the License.  \r\n");
      out.write(" * You may obtain a copy of the License at  \r\n");
      out.write(" *     \r\n");
      out.write(" *     http://www.apache.org/licenses/LICENSE-2.0  \r\n");
      out.write(" *     \r\n");
      out.write(" * Unless required by applicable law or agreed to in writing, software  \r\n");
      out.write(" * distributed under the License is distributed on an \"AS IS\" BASIS,  \r\n");
      out.write(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  \r\n");
      out.write(" * See the License for the specific language governing permissions and  \r\n");
      out.write(" * limitations under the License.\r\n");
      out.write(" */\r\n");
      out.write(" -->\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<div id=\"flowElementSuspension\" class=\"btn-group\">\r\n");
      out.write("\t<button id=\"elementEditBtn\" onclick=\"suspend('edit')\"  type=\"button\" class=\"btn btn-default\"><span class=\"glyphicon glyphicon-edit\"></span></button>\r\n");
      out.write("\t<button id=\"elementDeleteBtn\" onclick=\"suspend('delete')\" type=\"button\" class=\"btn btn-default\"><span class=\"glyphicon glyphicon-remove\"></span></button>\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button id=\"logOutBtn\" onclick=\"suspendConnector('output')\" type=\"button\" class=\"btn btn-default\"><span class=\"glyphicon glyphicon-log-out\"></span></button>\r\n");
      out.write("<!--  \t\t\t\r\n");
      out.write("\t\t<button id=\"elementSet\" onclick=\"suspend('set')\" type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-cog\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t<li><a id=\"nono\" href=\"#\" onclick=\"suspend('no')\">设置</a></li>\r\n");
      out.write("\t\t\t<li><a id=\"yesyes\" href=\"#\" onclick=\"suspend('yes')\">功能</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t  -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
